### ISSUE TITLE
Change default values for Navigation

### ISSUE THREAD

**Issue by bhhaskin** [OCG-labs/one-theme#15]
Change 
```php
    public $nav_left = false;
    public $nav_right = false;
```

to

```php
    public $nav_left = true;
    public $nav_right = true;
```

That way if you hook into the action there is no extra settings to turn them on, and you can still disable them if you want.

**Comment by mattie02** [comment]
these had been removed from the class in my last commit - https://github.com/OCG-labs/one-theme/commit/b6cc068b52743af8510299eddc046b7418bafa5d
